name: "Pull Target Files from Applanga (Workflow Trigger)"
on:
  workflow_dispatch:
    types: [applanga-pull]
jobs:
  pull-translation-in:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "Moses logging some changes"
         echo "The branch we are logging from is => ${{ github.event.client_payload.branchName }}"
         echo "$github.event.client_payload.branchName"
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branchName }}
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.1
        with:
          version: 1.0.48
      - name: Pull translations from Applanga
        env: 
         APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
        run: applanga pull
        working-directory: checkout
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: top-translation-changes
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: Updated translations
          title: Updated translations 
          body: Pulled in new translations from Applanga portal
          path: 'checkout'